version: '3.4'

services:
    springboot:
        build:  .
        restart: always
        container_name: bootdockercontainer
        ports: 
            - 8080:8080
        working_dir: /opt/app
        depends_on:
            - mongo
    mongo:
        image: hello_mongo
        container_name: mongodbcontainer
        ports: 
            - 27017:27017
        restart: always